version: '3.8'

services:
  python-backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile.python
    stdin_open: true
    tty: true
    ports:
      - "5000:8000"
    volumes:
      - ./python-backend/src:/app/src  # Mount only the src folder for development

  # electron-frontend:
  #   stdin_open: true
  #   tty: true
  #   build:
  #     context: ./electron-frontend
  #     dockerfile: Dockerfile.electron
  #   depends_on:
  #     - python-backend
  #   environment:
  #     - ELECTRON_BACKEND_URL=http://python-backend:5000
  #     - DISPLAY=$DISPLAY
  #   volumes:
  #     - ./electron-frontend:/app
  #     - $HOME/.Xauthority:/root/.Xauthority:rw
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - ~/.Xauthority:/root/.Xauthority
  #   network_mode: host
